import {
    IReservationFields, IReservationUpdateFields
} from "../../../interfaces/reservation/IReservationFields";


export const reservationFields: IReservationFields[] = [
    "GuestFirstname",
    "GuestName",
    "ProfileID",
    // "Guest3rdPartyID",
    "Name2",
    "GuestNum",
    "RoomType",
    "ReservationState",
    "ReservationStatus",
    "ReservationComment1",
    "ReservationComment2",
    "RoomNum",
    "GuestArrival",
    "GuestDeparture",
    "CheckinDateTime",
    "CheckoutDateTime",
    "ReservationType",
    "NoAvailReason",
    "PaymentMethod",
    "CrsSystem",
    "CrsResNumber",
    "NoOfRooms",
    "NoOfAdults",
    "RateCode",
    "RateValue",
    "ForeignRateValue",
    "ForeignTotalStay",
    "CurrencyCode",
    "MarketCode",
    "CompanyID",
    "TotalStay",
    "TravelAgentID",
    "SourceID",
    "BookerID",
    "CompanyName",
    "Share",
    "SourceName",
    "SourceCode",
    "TravelAgentName",
    "BookerName",
    "HasShare",
    "Child",
    "ChannelCode",
    "Guarantee",
    "GroupID",
    "GroupName",
    "BedReservation",
    "BlockCode",
    "NetRoomRevenue",
    // "DetailDate",
    // "ReservationDetails",
    "PartyID",
    "PartyName",
    "PartyMember",
    "PartyReservation",
    "ResStatusPriorCXL",
    "OptionDate",
    "Policy",
    "Hints",
    "LastUpdateTime",
    "CreationTime",
    "PackageCode",
    "Package",
    // "CustomField",
    // "AccompanyingGuests",
    // "AccompanyingGuest",
    // "ReservationAttribute",
    // "ReservationPreferences",
    // "NotesList",
    // "Notes",
];

export const reservationUpdateFields: IReservationUpdateFields[] = [
    "RoomType",
    "RoomNum",
    "GuestArrival",
    "GuestDeparture",
    "ReservationComment1",
    "ReservationComment2",
    "ProfileID",
    "PaymentMethod",
    "CrsSystem",
    "CrsResNumber",
    "NoOfRooms",
    "NoOfAdults",
    "RateCode",
    "RateValue",
    "ForeignRateValue",
    "CurrencyCode",
    "MarketCode",
    "CompanyID",
    "TravelAgentID",
    "SourceID",
    "BookerID",
    "ReservationAttribute",
    "Child",
    "SourceCode",
    "ChannelCode",
    "Guarantee",
    "GroupID",
    "CreditCardNo",
    "ExpiryMonth",
    "ExpiryYear",
    "CardholderName",
    "CreditCardCode",
    "ApprovalCode",
    "ApprovalAmount",
    "BlockCode",
    "OptionDate",
    "PackageCode",
    "CustomField",
    "Waitlist",
    "AccompanyingGuest",
    "ReservationPreference",
    "Policy",
    "Notes"
];

