import {IProfileFields} from "../../../interfaces/profile";


export const profileFields: IProfileFields[] = [
    "ProfileID",
    "ProfileGlobalID",
    "ProfileExternalID",
    // "Guest3rdPartyID",
    "GuestFirstname",
    "GuestName",
    "ProfileType",
    "ProfileCategory",
    "Title",
    "AddressGreeting",
    "LetterGreeting",
    "Birthday",
    "City",
    "Street1",
    "Street2",
    "Street3",
    "ZIP",
    "State",
    "CountryISO2",
    "CountryISO3",
    "Addresses",
    "Telephone",
    "Email",
    "Fax",
    "Communication",
    "Communications",
    "Gender",
    "DeleteCode",
    "NationalityISO2",
    "NationalityISO3",
    "Language",
    "VipCode",
    "Notes",
    "NotesList",
    "CreditStatus",
    "CreditReason",
    "LinkedProfile",
    "BirthPlace",
    "Department",
    "Position",
    "ProfileAttribute",

    "Membership",
    "PersonalDocument",
    "Notes",
    "ProfilePreferences",
    "ProfilePreference",
    "NoMailing",
    "NoEMailing",
    "GuestComment",
    "IncludeNotCommited",
    "CustomField",
    "CreditStatusChangeTime",
    "CentralSyncTime",
    "LastUpdateTime",
    "CreationTime",
];

